//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shoppers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Charge
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<double> Amount { get; set; }
        public string Description { get; set; }
        public string CategoryId { get; set; }
        public Nullable<int> CartId { get; set; }
    
        public virtual Cart Cart { get; set; }
        public virtual Category Category { get; set; }
    }
}
