//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shoppers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int Id { get; set; }
        public Nullable<int> Amount { get; set; }
        public string Sms { get; set; }
        public string Email { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string Currency { get; set; }
        public string ResultXML { get; set; }
        public string RefNo { get; set; }
        public Nullable<int> CartId { get; set; }
    
        public virtual Cart Cart { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
